package ASM1;


import java.awt.Color;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Vitinh TT2
 */
public class Login1 extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login1() {
        initComponents();
        setLocationRelativeTo(null);
        ClockThread th = new ClockThread(lblClock);
        th.start();
    }

    public void info(){
      
        
        txtUser.setText(Sharex.USERX.username);
        txtPass.setText(Sharex.USERX.password);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        lblQRcode = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        chkRemember = new javax.swing.JCheckBox();
        btnLogin = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\coollogo_com-21046355.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 400, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 240, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 240, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\USER ICON.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\pass icon.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 30, 40));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 200, 30));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, 30));

        lblQRcode.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblQRcode.setForeground(new java.awt.Color(0, 0, 153));
        lblQRcode.setText("QR code");
        lblQRcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQRcodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQRcodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQRcodeMouseExited(evt);
            }
        });
        jPanel1.add(lblQRcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, -1));

        btnRegister.setBackground(new java.awt.Color(51, 204, 0));
        btnRegister.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register now");
        btnRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 150, 40));

        chkRemember.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        chkRemember.setForeground(new java.awt.Color(0, 0, 204));
        chkRemember.setText("Remember me?");
        jPanel1.add(chkRemember, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 130, -1));

        btnLogin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(204, 0, 102));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 150, 40));

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 0, 51));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClock.setText("Clock");
        jPanel1.add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\background-đẹp-3-1024x682.jpg")); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean flag = true;
    private void lblQRcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRcodeMouseClicked
        // TODO add your handling code here:
        new SignIn().setVisible(true);
        flag = false;
    }//GEN-LAST:event_lblQRcodeMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnRegisterActionPerformed

    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        if(flag == false){
            info();
        }
        String username = txtUser.getText();
        String password = txtPass.getText();

        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String url = "jdbc:sqlserver://localhost:1433;databaseName=asmjava3";
                Connection con = DriverManager.getConnection(url, "sa", "123");
                PreparedStatement pst = con.prepareStatement("SELECT * FROM loginform WHERE username=? and password=?");

                pst.setString(1, username);
                pst.setString(2, password);
                ResultSet rs = pst.executeQuery();
                String user,pass,role,email;
                if (rs.next()) {
                    String s1 = rs.getString("role");
                    if (s1.equalsIgnoreCase("qlsv")) {
                        role = rs.getString("role");
                        email = rs.getString("email");
                        user = txtUser.getText();
                        pass = txtPass.getText();  
                        User u = new User(user, pass, role, email);
                        Share.USER = u;
                        QLSV qlsv = new QLSV();
                        JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                        if(chkRemember.isSelected() == true){
                            JOptionPane.showMessageDialog(this, "Đã ghi nhớ thông tin dăng nhập");
                        }
                        qlsv.setVisible(true);
                        setVisible(false);
                    }
                    if (s1.equalsIgnoreCase("qld")) {
                        role = rs.getString("role");
                        email = rs.getString("email");
                        user = txtUser.getText();
                        pass = txtPass.getText();  
                        User u = new User(user, pass, role, email);
                        Share.USER = u;
                        QLDiem qld = new QLDiem();
                        JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                        if(chkRemember.isSelected() == true){
                            JOptionPane.showMessageDialog(this, "Đã ghi nhớ thông tin dăng nhập");
                        }
                        qld.setVisible(true);
                        setVisible(false);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu");
                }

            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    
    private void lblQRcodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRcodeMouseEntered
        
        lblQRcode.setForeground(Color.red);
    }//GEN-LAST:event_lblQRcodeMouseEntered

    private void lblQRcodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRcodeMouseExited
        // TODO add your handling code here:
        lblQRcode.setForeground(Color.blue);
    }//GEN-LAST:event_lblQRcodeMouseExited

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jLabel1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox chkRemember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblQRcode;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
