/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASM1;



import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.opencv.core.Core;



/**
 *
 * @author Vitinh TT2
 */
public class QLSV extends javax.swing.JFrame {

    private String header[] = {"Mã SV", "Họ tên", "Email", "Số ĐT", "Giới tính",
        "Địa chỉ", "Hình"};
    SinhVien sinhVien;
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);

    /**
     * Creates new form QLSV
     */
    public QLSV() {
        initComponents();
        setLocationRelativeTo(null);
        showTable();
        DoDulieuLenComponent(0);
        info();
    }

    public void info(){
        lblUser.setText(Share.USER.username);
        lblPass.setText(Share.USER.role);
        lblEmail.setText(Share.USER.email);
    }
    public String info1(){
        
        String x = Sharey.USERY.info;
        return x;
    }
    public void UpdateHinh(String image) {
        ImageIcon image1 = new ImageIcon(image);
        Image im = image1.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_SMOOTH));
        lblHinh.setIcon(icon);

    }
    String url = "jdbc:sqlserver://localhost:1433;databaseName=asmjava3";

    public ArrayList<SinhVien> getSinhVienList(){
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
         ArrayList<SinhVien> sinhViens = new ArrayList<SinhVien>();
            
            String query = "SELECT * FROM SinhVien";
        try {
            con = DriverManager.getConnection(url, "sa", "123");
            st = con.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()){
                sinhVien = new SinhVien( rs.getString("MaSV"), rs.getString("HoTen"),
                        rs.getString("Email"), Integer.parseInt(rs.getString("SDT")), rs.getBoolean("GioiTinh"), rs.getString("DiaChi"),rs.getString("HinhAnh"));
                sinhViens.add(sinhVien);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLSV.class.getName()).log(Level.SEVERE, null, ex);
        }
      return sinhViens;
    }
    public void showTable(){
        ArrayList<SinhVien> list = getSinhVienList();
        DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
        //clead khi chạy không chồng dữ liệu lên nhau
        model.setRowCount(0);
        Object[] row = new Object[7];
        for(int i =0;i<list.size();i++){
            row[0] = list.get(i).getMaSV();
            row[1] = list.get(i).getHoTen();
            row[2] = list.get(i).getEmail();
            row[3] = list.get(i).getSDT();
            row[4] = list.get(i).isGioitinh();
            row[5] = list.get(i).getDiaChi();
            row[6] = list.get(i).getHinhanh();
            model.addRow(row);
        }
    }
    



/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        btnChupHinh = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bntIcon = new javax.swing.JButton();
        bntSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        bntdetele = new javax.swing.JButton();
        bntdetele1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bntfirst = new javax.swing.JButton();
        bntprevious = new javax.swing.JButton();
        bntnext = new javax.swing.JButton();
        bntlast = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\LOGO QLSV.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 432, 77));

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ tên", "Email", "SĐT", "Giới tính", "Địa chỉ", "Hình ảnh"
            }
        ));
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSinhVien);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 550, 810, 130));

        jPanel1.setBackground(new java.awt.Color(240, 206, 213));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnChupHinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnChupHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Slide4/images/camera-icon.png"))); // NOI18N
        btnChupHinh.setText("Chụp hình");
        btnChupHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChupHinhActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\Pictures-icon.png")); // NOI18N
        jButton2.setText("Chọn hình");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChupHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChupHinh)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 122, -1, 350));

        jPanel2.setBackground(new java.awt.Color(240, 198, 212));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bntIcon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_add.png"))); // NOI18N
        bntIcon.setText("New");
        bntIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIconActionPerformed(evt);
            }
        });

        bntSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_save.png"))); // NOI18N
        bntSave.setText("Save");
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        bntdetele.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntdetele.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_delete.png"))); // NOI18N
        bntdetele.setText("Delete");
        bntdetele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdeteleActionPerformed(evt);
            }
        });

        bntdetele1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntdetele1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\Log-Out-icon.png")); // NOI18N
        bntdetele1.setText("Log out");
        bntdetele1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdetele1ActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\Button-Cancel-icon.png")); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntdetele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntdetele1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bntSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bntIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(bntIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(bntdetele, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntdetele1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 122, -1, 350));

        jPanel4.setBackground(new java.awt.Color(240, 208, 226));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mã SV:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Họ Tên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("SĐT:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Giới Tính:");

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Địa Chỉ:");

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdoNam)
                        .addGap(46, 46, 46)
                        .addComponent(rdoNu))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSDT)
                        .addComponent(txtHoTen)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaSv)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSDT)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 350));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Edit");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 40, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Hình ảnh minh họa");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 94, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Thông tin cá nhân");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 94, -1, -1));

        bntfirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon10.png"))); // NOI18N
        bntfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntfirstActionPerformed(evt);
            }
        });
        getContentPane().add(bntfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 50, 32));

        bntprevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon8.png"))); // NOI18N
        bntprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntpreviousActionPerformed(evt);
            }
        });
        getContentPane().add(bntprevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 50, 32));

        bntnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon7.png"))); // NOI18N
        bntnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntnextActionPerformed(evt);
            }
        });
        getContentPane().add(bntnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 50, 32));

        bntlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon9.png"))); // NOI18N
        bntlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntlastActionPerformed(evt);
            }
        });
        getContentPane().add(bntlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 50, 32));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Role :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("User :");

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 102, 0));

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 190, 80));

        lblEmail.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\background.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void DoDulieuLenComponent(int row){
        if(row < 0){
            return;
        }
        txtMaSv.setText(tblSinhVien.getValueAt(row, 0).toString());
        txtHoTen.setText(tblSinhVien.getValueAt(row, 1).toString());
        txtEmail.setText(tblSinhVien.getValueAt(row, 2).toString());
        txtSDT.setText(tblSinhVien.getValueAt(row, 3).toString());
        Boolean gioitinh = Boolean.parseBoolean(tblSinhVien.getValueAt(row, 4).toString());
        if(gioitinh){
            rdoNam.setSelected(true);
        }else
            rdoNu.setSelected(false);
        txtDiaChi.setText(tblSinhVien.getValueAt(row, 5).toString());
        UpdateHinh(tblSinhVien.getValueAt(row, 6).toString());
    }
    private void bntdeteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdeteleActionPerformed
        if (txtMaSv.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Nhập mã sinh viên");
            txtMaSv.requestFocus();
            txtMaSv.setText(null);
        }
        try {
            int r = JOptionPane.showConfirmDialog(this, "Bạn thật sự muốn xóa?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION)
            {
                Connection con = DriverManager.getConnection(url, "sa", "123");
                String sql  = "delete from SINHVIEN where MASV = ?";
                PreparedStatement st = con.prepareStatement(sql);
                st.setString(1, txtMaSv.getText());
                st.execute();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                clearText();
                DoDulieuLenComponent(0);
                showTable();
                con.close();
            }
        } 
        catch (Exception e) 
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Lỗi!");
        }
    }//GEN-LAST:event_bntdeteleActionPerformed

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblHinhMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (txtMaSv.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Nhập mã sinh viên");
            txtMaSv.requestFocus();
            txtMaSv.setText(null);
        }
        try 
        {
            Connection con = DriverManager.getConnection(url, "sa", "123");
            String sql  = "update SINHVIEN set HOTEN = ?, EMAIL = ?, SDT = ?, GIOITINH = ?, DIACHI = ?, hinhanh = ? where MASV = ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, txtHoTen.getText());
            st.setString(2, txtEmail.getText());
            st.setString(3, txtSDT.getText());
            boolean gt = false;
            if (rdoNam.isSelected())
                gt = true;
            else
                gt = false;
            st.setBoolean(4, gt);
            st.setString(5, txtDiaChi.getText());
            st.setString(6, duongdananh); 
          
            st.setString(7, txtMaSv.getText());   
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            
            showTable();
            con.close();
            flag = true;
        } 
        catch (Exception e) 
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Lỗi!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
        // TODO add your handling code here:
        if (txtMaSv.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Không bỏ trống mã sinh viên.");
            txtMaSv.requestFocus();
        }
        else
        {
            try 
            {
                Connection con = DriverManager.getConnection(url, "sa", "123");
                String sql  = "insert into SINHVIEN(MaSV, HoTen, Email, SDT, GioiTinh, DiaChi, HinhAnh) values(?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement st = con.prepareStatement(sql);
                st.setString(1, txtMaSv.getText());
                st.setString(2, txtHoTen.getText());
                st.setString(3, txtEmail.getText());
                st.setString(4, txtSDT.getText());
                boolean gt = false;
                if (rdoNam.isSelected())
                    gt = true;
                else
                    gt = false;
                st.setBoolean(5, gt);
                st.setString(6, txtDiaChi.getText());
                st.setString(7, duongdananh);
                st.execute();
                JOptionPane.showMessageDialog(this, "Lưu thành công!");
                clearText();
                DoDulieuLenComponent(0);
                showTable();
                con.close();
            } 
            catch (Exception ex) 
            {
                System.out.println(ex);
                JOptionPane.showMessageDialog(this, "Lưu thất bại!");
            }
        }

    }//GEN-LAST:event_bntSaveActionPerformed

    private void bntIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIconActionPerformed
        // TODO add your handling code here:     
        clearText();
    }//GEN-LAST:event_bntIconActionPerformed
    void clearText()
    {
        txtMaSv.setText(null);
        txtHoTen.setText(null);
        txtEmail.setText(null);
        txtSDT.setText(null);
        rdoNu.setSelected(false);
        rdoNam.setSelected(true);
        txtDiaChi.setText(null);
        UpdateHinh("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\default.jpg");
    }
    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        // TODO add your handling code here:
        int row = tblSinhVien.getSelectedRow();
        DoDulieuLenComponent(row);
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void bntdetele1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdetele1ActionPerformed
        // TODO add your handling code here:
        new Login1().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_bntdetele1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    int currentIndex = 0;
    
    private void bntfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntfirstActionPerformed
        // TODO add your handling code here:
        ArrayList<SinhVien> list = getSinhVienList();
        try {
            currentIndex = 0;
            DoDulieuLenComponent(currentIndex);
            tblSinhVien.changeSelection(currentIndex, 1, false, false);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_bntfirstActionPerformed

    
    private void bntpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntpreviousActionPerformed
        // TODO add your handling code here:
        ArrayList<SinhVien> list = getSinhVienList();
        try {
            currentIndex--;
            if (currentIndex < 0) {
                JOptionPane.showMessageDialog(this, "Bạn đang ở đầu!");
                currentIndex = 0;
                return;
            }
            DoDulieuLenComponent(currentIndex);
            tblSinhVien.changeSelection(currentIndex, 1, false, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bntpreviousActionPerformed

    private void bntnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntnextActionPerformed
        // TODO add your handling code here:
            ArrayList<SinhVien> list = getSinhVienList();
            try {
            currentIndex++;
            if (currentIndex >= list.size()) {
                JOptionPane.showMessageDialog(this, "Bạn đang ở cuối!");
                currentIndex = list.size()-1;
                return;
            }
            DoDulieuLenComponent(currentIndex);
            tblSinhVien.changeSelection(currentIndex, 1, false, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_bntnextActionPerformed

    private void bntlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntlastActionPerformed
        // TODO add your handling code here:
        ArrayList<SinhVien> list = getSinhVienList();
        try {
            currentIndex = list.size() - 1;
            DoDulieuLenComponent(currentIndex);
            tblSinhVien.changeSelection(currentIndex, 1, false, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bntlastActionPerformed

    private String ChonFile() {
        String duongDan = "";
        JFileChooser c = new JFileChooser();
        int val = c.showOpenDialog(null);
        if (val == JFileChooser.APPROVE_OPTION) {
            String tenFile = c.getSelectedFile().getName();
            String tenODia = c.getCurrentDirectory().toString();
            duongDan = tenODia + "\\" + tenFile;
            JOptionPane.showMessageDialog(this, "Chọn File thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn File nào!!");
            duongDan = "AVATAR";
        }
        return duongDan;
    }
    String duongdananh = "C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\default.jpg";
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(flag == true)
            duongdananh = ChonFile();
        if(flag == false){
            duongdananh = info1();
            
        }
        lblHinh.setIcon(SelectImage(duongdananh));
        
    }//GEN-LAST:event_jButton2ActionPerformed
    boolean flag = true;
    private void btnChupHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChupHinhActionPerformed
        // TODO add your handling code here:
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        new Capture().setVisible(true);
        flag = false;

        
    }//GEN-LAST:event_btnChupHinhActionPerformed
    private ImageIcon SelectImage(String path) {
        ImageIcon MyImage = new ImageIcon(path);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntIcon;
    private javax.swing.JButton bntSave;
    private javax.swing.JButton bntdetele;
    private javax.swing.JButton bntdetele1;
    private javax.swing.JButton bntfirst;
    private javax.swing.JButton bntlast;
    private javax.swing.JButton bntnext;
    private javax.swing.JButton bntprevious;
    private javax.swing.JButton btnChupHinh;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSv;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
