package ASM1;

import Model.Grade;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.NotFoundException;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.ResultSet;

import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Vitinh TT2
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
        setLocationRelativeTo(null);
        ThemList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtComfirm = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        cboRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        chkAccept = new javax.swing.JCheckBox();
        btnRegister1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\coollogoRegister.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 310, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 240, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 240, 10));

        txtComfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtComfirm.setText("Confirm password");
        txtComfirm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtComfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtComfirmMouseClicked(evt);
            }
        });
        txtComfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComfirmActionPerformed(evt);
            }
        });
        jPanel1.add(txtComfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 240, 30));

        btnRegister.setBackground(new java.awt.Color(0, 255, 255));
        btnRegister.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 51, 51));
        btnRegister.setText("Register now");
        btnRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 150, 40));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUser.setText("User name");
        txtUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 240, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 240, 10));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass.setText("Password");
        txtPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassMouseClicked(evt);
            }
        });
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 240, 30));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setText("Email address");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 240, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 240, 10));

        cboRole.setBackground(new java.awt.Color(102, 0, 102));
        cboRole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboRole.setForeground(new java.awt.Color(255, 0, 0));
        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý sinh viên", "Quản lý điểm" }));
        jPanel1.add(cboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 160, 40));

        jLabel3.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Role:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 70, 40));

        chkAccept.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        chkAccept.setForeground(new java.awt.Color(0, 102, 102));
        chkAccept.setText("Tôi đồng ý với tất cả điều khoản dịch vụ");
        jPanel1.add(chkAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 260, -1));

        btnRegister1.setBackground(new java.awt.Color(51, 51, 51));
        btnRegister1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnRegister1.setForeground(new java.awt.Color(204, 255, 255));
        btnRegister1.setText("Back to login");
        btnRegister1.setBorder(null);
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vitinh TT2\\Desktop\\Lab_java\\BuiDucMinh\\src\\Slide4\\images\\backgroundregister.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtComfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComfirmActionPerformed

    public void createQR(String data, String path,
            String charset, Map hashMap,
            int height, int width)
            throws WriterException, IOException {

        BitMatrix matrix = new MultiFormatWriter().encode(
                new String(data.getBytes(charset), charset),
                BarcodeFormat.QR_CODE, width, height);

        MatrixToImageWriter.writeToFile(
                matrix,
                path.substring(path.lastIndexOf('.') + 1),
                new File(path));
    }

    public void GenerateQR(String user, String pass) throws WriterException, IOException, NotFoundException {
        // The data that the QR code will contain
        String data1 = user +"|"+ pass;

        // The path where the image will get saved
        String path = "C:\\Users\\Vitinh TT2\\Desktop\\QRcode\\account.png";

        // Encoding charset
        String charset = "UTF-8";

        Map<EncodeHintType, ErrorCorrectionLevel> hashMap
                = new HashMap<EncodeHintType, ErrorCorrectionLevel>();

        hashMap.put(EncodeHintType.ERROR_CORRECTION,
                ErrorCorrectionLevel.L);

        // Create the QR code and save
        // in the specified folder
        // as a jpg file
        createQR(data1, path, charset, hashMap, 200, 200);
        System.out.println("Text QR : " + data1);
        System.out.println("QR Code Generated!!! ");
    }
    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        if (txtUser.getText().equals("User name")) {
            txtUser.setText("");
        }

        if (txtPass.getText().equals("")) {
            txtPass.setText("Password");
        }
        if (txtComfirm.getText().equals("")) {
            txtComfirm.setText("Confirm password");
        }
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Email address");
        }
    }//GEN-LAST:event_txtUserMouseClicked

    Connection con;
    ResultSet rs;
    Statement st;
    Grade grade;
    String url = "jdbc:sqlserver://localhost:1433;databaseName=asmjava3";
    ArrayList<Account> list = new ArrayList<>();
    public void ThemList()
    {
        try 
        {
            Connection con = DriverManager.getConnection(url, "sa", "123");
            Statement st = con.createStatement();
            String sql  = "Select * from loginform";
            ResultSet rs = st.executeQuery(sql);
            list.clear();
            while(rs.next())
            {
                int id = rs.getInt(1);
                String username = rs.getString(2);
                String password = rs.getString(3);
                String role = rs.getString(4);
                String email = rs.getString(5);
                Account acc = new Account(id, username, password, role, email);
                list.add(acc);
            }
            con.close();
        } 
        catch (Exception ex) 
        {
            System.out.println(ex);
        }
    }
    boolean flag = true;
    public boolean Search(){
        
        String user = txtUser.getText();
        int i;
        for (i = 0; i < list.size(); i++) {
            Account acc = list.get(i);
            if (acc.getUsername().equals(user)) {
                
                flag = false;
                break;
            }
        }
        return flag;
    }
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        if (txtUser.getText().equals("User name") || txtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập username");
            txtUser.requestFocus();
            return;
        }
        if (txtPass.getText().equals("Password") || txtPass.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập password");
            txtPass.requestFocus();
            return;
        }
        if (txtComfirm.getText().equals("Confirm password") || txtComfirm.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập Confirm");
            txtComfirm.requestFocus();
            return;
        }
        if (txtEmail.getText().equals("Email address") || txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập email");
            txtEmail.requestFocus();
            return;
        }
        String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        if (!txtEmail.getText().matches(regex)) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ!");
            return;
        }
        if (!txtPass.getText().equals(txtComfirm.getText())) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không khớp vui lòng nhập lại");
            txtPass.requestFocus();
            return;
        }
        if (!chkAccept.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng đồng ý với các điều khoản dịch vụ ");
            return;
        }
        if(Search() == false){
            JOptionPane.showMessageDialog(this, "Tên đăng nhập đã tồn tại ");
            flag = true;
            return;
        }
        JOptionPane.showMessageDialog(this, "Đăng kí thành công");

        String user = txtUser.getText();
        String pass = txtPass.getText();
        String role = cboRole.getSelectedIndex() == 0 ? "qlsv" : "qld";
        String email = txtEmail.getText();

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=asmjava3";
            Connection con = DriverManager.getConnection(url, "sa", "123");
            Statement stm = con.createStatement();
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = s.executeQuery("SELECT * FROM loginform");

            rs.last();
            int id = rs.getRow() + 1;
            String sql = "insert loginform values (" + id + ", '" + user + "', '" + pass + "', '" + role + "', '" + email + "')";
            int rows = stm.executeUpdate(sql);
            GenerateQR(user, pass);
        } catch (Exception ex) {
            System.out.println(ex);
        }

        new Login1().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseClicked
        // TODO add your handling code here:
        if (txtPass.getText().equals("Password")) {
            txtPass.setText("");
        }

        if (txtUser.getText().equals("")) {
            txtUser.setText("User name");
        }
        if (txtComfirm.getText().equals("")) {
            txtComfirm.setText("Confirm password");
        }
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Email address");
        }

    }//GEN-LAST:event_txtPassMouseClicked

    private void txtComfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtComfirmMouseClicked
        // TODO add your handling code here:
        if (txtComfirm.getText().equals("Confirm password")) {
            txtComfirm.setText("");
        }

        if (txtPass.getText().equals("")) {
            txtPass.setText("Password");
        }
        if (txtUser.getText().equals("")) {
            txtUser.setText("User name");
        }
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Email address");
        }
    }//GEN-LAST:event_txtComfirmMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
        if (txtEmail.getText().equals("Email address")) {
            txtEmail.setText("");
        }

        if (txtPass.getText().equals("")) {
            txtPass.setText("Password");
        }
        if (txtComfirm.getText().equals("")) {
            txtComfirm.setText("Confirm password");
        }
        if (txtUser.getText().equals("")) {
            txtUser.setText("User name");
        }
    }//GEN-LAST:event_txtEmailMouseClicked

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        // TODO add your handling code here:
        new Login1().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnRegister1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegister1;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JCheckBox chkAccept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtComfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
